version: '2.1'
services:
  config:
    build: ./config/
    restart: always
    networks:
     - back
    healthcheck:
        test: curl -f http://localhost:8888/annuaire/default && echo 'cool, it works'
        interval: 10s
        timeout: 10s
        retries: 5
    ports:
     - "8888:8888"
  annuaire:
    build: ./annuaire/
    networks:
     - back
    ports:
     - "1111:1111"
    restart: always
    depends_on:
      config: 
        condition: service_healthy
  document-service:
    build: ./document-service/
    networks:
     - back
    restart: always
    depends_on:
      config: 
        condition: service_healthy
  notification-service:
    build: ./notification-service/
    networks:
     - back
    restart: always
    depends_on:
      config: 
        condition: service_healthy
  members-service:
    build: ./members-service/
    networks:
      - back
    restart: always
    depends_on:
      - config
  turbine:
    build: ./turbine/
    networks:
      - back
    restart: always
    depends_on:
      config: 
        condition: service_healthy
    ports:
     - "5555:5555"
  proxy:
    build: ./proxy/
    networks:
      - front
      - back
    ports:
      - 8081:8081
    restart: always
    depends_on:
      config: 
        condition: service_healthy
  fake-smtp:
    build: ./fake-smtp/
    networks:
      - back
  angular:
    build: ./angular
    networks:
      - front
    ports:
      - 81:80


networks:
  back:
  front:
